<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="mrane" name="Test" tests="6" failures="2" timestamp="5 Oct 2018 08:56:35 GMT" time="6.541" errors="0">
  <testcase name="login" time="0.506" classname="LoginModuleTests.DataDrivenLoginTests"/>
  <testcase name="login" time="0.269" classname="LoginModuleTests.DataDrivenLoginTests"/>
  <testcase name="login" time="0.218" classname="LoginModuleTests.DataDrivenLoginTests"/>
  <testcase name="login" time="0.297" classname="LoginModuleTests.DataDrivenLoginTests"/>
  <testcase name="invalidLogin" time="1.282" classname="LoginModuleTests.LoginTests">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at LoginModuleTests.LoginTests.invalidLogin(LoginTests.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
  <testcase name="invalidLogin" time="1.284" classname="LoginModuleTests.LoginTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at listeners.ExtentReportListener.onTestFailure(ExtentReportListener.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
</testsuite> <!-- Test -->
